---
application1:
  API_GATEWAY:
    - name: simple-api-prod
      base_path: /api/simple
      target_url: https://internal-service:8080
    # - name: user-service-prod
    #   base_path: /api/users
    #   target_url: https://internal-user-service:8443
    #   methods:
    #     - GET
    #     - POST
    #     - PUT
    #     - DELETE
    #   rate_limit:
    #     requests_per_minute: 1000
    #     burst_size: 100
    #   authentication: jwt
    #   cors:
    #     enabled: true
    #     allowed_origins:
    #       - https://app.example.com
    #       - https://admin.example.com
    #     allowed_methods:
    #       - GET
    #       - POST
    #       - PUT
    #       - DELETE
    #       - OPTIONS
    #     allowed_headers:
    #       - Content-Type
    #       - Authorization
    #       - X-Requested-With 